
version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=archmage
      - MYSQL_DATABASE=dailyAMC
    ports:
      - "3306:3306"
    restart: always
    networks:
      - app-network

  app:
    container_name: fast_api
    build: ./app
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
      - "587:587"
    env_file:
      - .env
    environment:
      - APP_SECRET_STRING=archmage
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=archmage
      - DATABASE=dailyAMC
      - DATABASE_HOST=mysql
    depends_on:
      - mysql
    command: /app/wait-for-mysql.sh mysql "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:
