version: '3'
services:
  mysql:
    container_name: mysql
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=archmage
      - MYSQL_DATABASE=dailyAMC
    tty: true
  app:
    depends_on:
      - mysql
    container_name: fast_api
    command: /app/wait-for-mysql.sh mysql "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    build: ./app
    restart: always
    tty: true
    volumes:
      - ./app:/app
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    environment:
      - APP_SECRET_STRING=archmage
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=archmage
      - DATABASE=dailyAMC
      - DATABASE_HOST=mysql
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    restart: always
    networks:
      - my-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot --webroot-path=/var/www/certbot --email your.email@example.com --agree-tos -d yourdomain.com -d www.yourdomain.com; sleep 12h & wait $${!}; done;'"


networks:
  my-network:
    external: true