version: '3'
services:
  mysql:
    container_name: mysql
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=archmage
      - MYSQL_DATABASE=dailyAMC
    tty: true
  app:
#    command: bash -c "sleep 20 && uvicorn main:app --reload --host 0.0.0.0 --port 8000"

    depends_on:
      - mysql
#    depends_on:
#      rabbit:
#        condition: service_healthy
    container_name: fast_api

    command: /app/wait-for-mysql.sh mysql "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    build: ./app
    restart: always
    tty: true
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - APP_SECRET_STRING=archmage
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=archmage
      - DATABASE=dailyAMC
      - DATABASE_HOST=mysql