version: '3'

services:
  mysql:
    container_name: mysql
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=archmage
      - MYSQL_DATABASE=dailyAMC
    tty: true

  app:
    depends_on:
      - mysql
    container_name: fast_api
    command: /app/wait-for-mysql.sh mysql "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    build: ./app
    restart: always
    tty: true
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    environment:
      - APP_SECRET_STRING=archmage
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=archmage
      - DATABASE=dailyAMC
      - DATABASE_HOST=mysql

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/letsencrypt/live/dailyamc.xyz
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - app
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  certbot:
    image: certbot/dns-digitalocean
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email notforworked@gmail.com --agree-tos --no-eff-email --staging --dns-digitalocean --dns-digitalocean-credentials /run/secrets/digitalocean.ini -d dailyamc.xyz

secrets:
  digitalocean:
    external: true