version: '3'
services:
  mysql:
    container_name: mysql
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=archmage
      - MYSQL_DATABASE=dailyAMC
    tty: true
    networks:
      - appnet

  app:
    depends_on:
      - mysql
    container_name: fast_api
    command: /app/wait-for-mysql.sh mysql "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    build: ./app
    restart: always
    tty: true
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    environment:
      - APP_SECRET_STRING=archmage
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=archmage
      - DATABASE=dailyAMC
      - DATABASE_HOST=mysql
    networks:
      - appnet

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - appnet

networks:
  appnet:
